name: Cache Dependencies

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Prime cache
      - name: prime-cache-a2fe9dd
        id: prime-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: cache-a2fe9dd

      # Step 3: Show cache hit/miss
      - name: Cache result
        run: echo "Cache hit: ${{ steps.prime-cache.outputs.cache-hit }}"
